import { useParams, Link } from "react-router-dom";
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SocialSidebar from "@/components/SocialSidebar";
import { blogs } from "@/data/blogs";
import { getDailyLocalInsights } from "@/data/dailyLocalInsights";
import SEO, { createBlogPostSchema } from "@/components/SEO";

const BlogPost=()=>{const{slug}=useParams<{slug:string}>();const all=[...getDailyLocalInsights(),...blogs];const blog=all.find(b=>b.slug===slug);const isFuturePost=blog&&new Date(blog.date)>new Date();
if(!blog||isFuturePost)return <div className="flex flex-col min-h-screen bg-background"><SEO title="Blog Not Found | KidSalonia" description="The blog post you're looking for could not be found." noIndex/><Header/><div className="flex-1 flex items-center justify-center"><div className="text-center"><h1 className="text-3xl font-bold mb-4">Blog Not Found</h1><Link to="/insights" className="text-primary hover:underline">← Back to Insights</Link></div></div><Footer/></div>;
const inline=(text:string):React.ReactNode[]=>text.split(/(\*\*.*?\*\*|\[.*?\]\(.*?\))/g).map((part,j)=>{if(part.startsWith("**")&&part.endsWith("**"))return <strong key={j}>{part.slice(2,-2)}</strong>;const m=part.match(/^\[(.*?)\]\((.*?)\)$/);if(m){const[,t,u]=m;return u.startsWith("/")||u.startsWith("#")?<Link key={j} to={u} className="text-primary hover:underline font-medium">{t}</Link>:<a key={j} href={u} className="text-primary hover:underline font-medium" target="_blank" rel="noopener noreferrer">{t}</a>}return <span key={j}>{part}</span>});
const render=(content:string)=>content.split("\n\n").map((block,i)=>{if(block.startsWith("## "))return <h2 key={i} className="text-2xl font-black text-[#4b2677] mt-8 mb-4">{inline(block.slice(3))}</h2>;if(block.startsWith("- "))return <ul key={i} className="list-disc pl-6 space-y-2 text-foreground/80 leading-relaxed">{block.split("\n- ").map((x,j)=><li key={j}>{inline(x.replace(/^- /,""))}</li>)}</ul>;return <p key={i} className="text-foreground/80 leading-relaxed mb-4">{inline(block)}</p>});
return <div className="flex flex-col min-h-screen bg-gradient-to-b from-pink-50 to-sky-50"><SEO title={`${blog.title} | KidSalonia`} description={blog.excerpt} canonical={`https://www.kidsalonia.com/insights/${blog.slug}`} ogType="article" jsonLd={createBlogPostSchema(blog)}/><Header/><SocialSidebar/><div className="w-full max-w-4xl mx-auto px-4 pt-8"><img src={blog.image} alt={blog.title} className="w-full h-[300px] md:h-[420px] object-cover rounded-[2rem] shadow-lg"/></div><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-6"><div className="flex flex-wrap gap-3 text-sm text-muted-foreground mb-4"><span>📅 {blog.date}</span><span>✍️ {blog.author}</span><span>⏱ {blog.readTime}</span><span>📚 {blog.category}</span></div><h1 className="text-3xl md:text-4xl font-black text-[#3f216f] mb-8">{blog.title}</h1><article className="rounded-[2rem] bg-white/90 p-6 md:p-10 shadow-sm mb-10">{render(blog.content)}</article><div className="pb-12"><Link to="/insights" className="text-primary hover:underline font-bold">← Back to All Insights</Link></div></div><Footer/></div>};
export default BlogPost;
