import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { CheckCircle2, Scissors, Sparkles, Footprints } from "lucide-react";
import { toast } from "sonner";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SocialSidebar from "@/components/SocialSidebar";
import SEO from "@/components/SEO";
import { BOOKING_SERVICES, getIndiaDate, getSlotsForDate, isPastSlot, isTuesday, isValidEmail, isValidPhone } from "@/lib/booking";

const API_URL="https://kidsalonia-ai.vercel.app", WHATSAPP="918130307036";
type AvailabilityState="idle"|"loading"|"ready"|"error";
type Category="hair"|"nail"|"pedi-mani";
const GROUPS=[
 {id:"hair" as Category,label:"Hair",artist:"Rajiv",subtitle:"Haircut by Rajiv",icon:Scissors,slugs:["kids-haircut","baby-first-haircut","boy-haircut","girl-haircut","adult-haircut","mundan","hair-wash","hair-styling","hair-spa","lice-treatment"]},
 {id:"nail" as Category,label:"Nails",artist:"Pooja",subtitle:"Nail Art by Pooja",icon:Sparkles,slugs:["kids-nail-art","adult-nail-art","gel-polish"]},
 {id:"pedi-mani" as Category,label:"Mani & Pedi",artist:"Julie",subtitle:"Manicure & Pedicure by Julie",icon:Footprints,slugs:["kids-manicure","adult-manicure","kids-pedicure","adult-pedicure"]},
];
const groupFor=(slug:string)=>GROUPS.find(g=>g.slugs.includes(slug));
const errorMessage=(r:unknown,f:string)=>r&&typeof r==="object"&&"message" in r&&typeof r.message==="string"?r.message:f;

export default function BookingV2(){
 const [params]=useSearchParams(); const requested=params.get("service")??""; const initial=BOOKING_SERVICES.some(s=>s.slug===requested)?requested:""; const initialGroup=groupFor(initial);
 const [step,setStep]=useState(initial?2:1),[category,setCategory]=useState<Category|"">(initialGroup?.id??""),[submitting,setSubmitting]=useState(false),[availability,setAvailability]=useState<AvailabilityState>("idle"),[blocked,setBlocked]=useState<string[]>([]),[reference,setReference]=useState("");
 const [form,setForm]=useState({service:initial,customerName:"",age:"",contactName:"",phone:"",email:"",date:"",time:"",mundanLocation:"",homeAddress:""});
 const service=useMemo(()=>BOOKING_SERVICES.find(s=>s.slug===form.service),[form.service]); const group=groupFor(form.service); const artist=group?.artist??""; const services=GROUPS.find(g=>g.id===category)?.slugs.map(slug=>BOOKING_SERVICES.find(s=>s.slug===slug)).filter(Boolean)??[]; const slots=useMemo(()=>getSlotsForDate(form.date),[form.date]); const isMundan=form.service==="mundan";
 useEffect(()=>{if(!form.date||!service||!artist||isTuesday(form.date)){setBlocked([]);setAvailability("idle");return;}const c=new AbortController();(async()=>{setAvailability("loading");try{const r=await Promise.all(slots.map(async([time])=>{if(isPastSlot(form.date,time))return time;const q=new URLSearchParams({date:form.date,time,stylist:artist,duration:String(service.duration)});const x=await fetch(`${API_URL}/api/appointments/availability?${q}`,{cache:"no-store",headers:{Accept:"application/json"},signal:c.signal});const j:any=await x.json().catch(()=>null);return x.ok&&j?.available===true?null:time;}));setBlocked(r.filter((x):x is string=>Boolean(x)));setAvailability("ready");}catch(e){if(e instanceof DOMException&&e.name==="AbortError")return;setAvailability("error");}})();return()=>c.abort();},[form.date,service,artist,slots]);
 const validateDetails=()=>{if(!form.customerName.trim()||!form.phone.trim())return"Please enter customer name and mobile number.";if(!isValidPhone(form.phone))return"Enter a valid 10-digit Indian mobile number.";if(!isValidEmail(form.email))return"Enter a valid email address.";if(isMundan&&!form.mundanLocation)return"Please select Mundan location.";if(isMundan&&form.mundanLocation==="Home"&&!form.homeAddress.trim())return"Please enter the home address.";return null;};
 const submit=async()=>{if(!service||!artist||submitting)return;const e=validateDetails();if(e)return toast.error(e);setSubmitting(true);try{const q=new URLSearchParams({date:form.date,time:form.time,stylist:artist,duration:String(service.duration)});const a=await fetch(`${API_URL}/api/appointments/availability?${q}`,{cache:"no-store",headers:{Accept:"application/json"}});const aj:any=await a.json().catch(()=>null);if(!(a.ok&&aj?.available===true))throw new Error("That slot was just booked. Please choose another time.");const r=await fetch(`${API_URL}/api/appointments/website-booking`,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({parentName:(form.contactName||form.customerName).trim(),childName:form.customerName.trim(),childAge:form.age.trim(),phone:form.phone.trim(),email:form.email.trim()||undefined,service:service.name,stylist:artist,date:form.date,time:form.time,duration:service.duration,mundanLocation:isMundan?form.mundanLocation:undefined,homeAddress:isMundan&&form.mundanLocation==="Home"?form.homeAddress.trim():undefined})});const j:any=await r.json().catch(()=>null);if(!(r.ok&&j?.success===true))throw new Error(errorMessage(j,"Unable to complete booking."));setReference(String(j.appointmentId||`KS-${Date.now().toString().slice(-8)}`));toast.success("Appointment booked successfully.");window.scrollTo({top:0,behavior:"smooth"});}catch(e){toast.error(e instanceof Error?e.message:"Unable to complete booking.");setStep(2);}finally{setSubmitting(false);}};
 if(reference&&service)return <div className="min-h-screen bg-background"><SEO title="Booking Confirmed | KidSalonia" description="Your KidSalonia appointment is confirmed." canonical="https://www.kidsalonia.com/book" noIndex/><Header/><main className="mx-auto max-w-3xl px-4 py-16 text-center"><CheckCircle2 className="mx-auto h-20 w-20 text-emerald-500"/><h1 className="mt-6 text-4xl font-extrabold">Appointment booked!</h1><div className="mx-auto mt-8 max-w-xl rounded-3xl border bg-card p-7 text-left"><p><b>Reference:</b> {reference}</p><p className="mt-2"><b>{service.name}</b> with {artist}</p><p className="mt-2">{form.date} at {form.time}</p></div><a className="mt-7 inline-block rounded-full bg-emerald-500 px-6 py-3 font-bold text-white" href={`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`Hi KidSalonia, booking ${reference} for ${service.name} with ${artist} is confirmed for ${form.date} at ${form.time}.`)}`}>WhatsApp confirmation</a></main><Footer/></div>;
 const selectCategory=(id:Category)=>{setCategory(id);setForm({...form,service:"",date:"",time:"",mundanLocation:"",homeAddress:""});};
 const chooseService=(slug:string)=>{setForm({...form,service:slug,date:"",time:"",mundanLocation:"",homeAddress:""});};
 const goSlot=()=>{if(!service)return toast.error("Choose a service first.");setStep(2);};
 const goDetails=()=>{if(!form.date||!form.time)return toast.error("Choose a date and available time.");setStep(3);};
 return <div className="min-h-screen bg-gradient-to-b from-pink-50 via-white to-orange-50"><SEO title="Book Salon Appointment in Gurgaon | KidSalonia" description="Fast online booking at KidSalonia Gurgaon." canonical="https://www.kidsalonia.com/book"/><Header/><SocialSidebar/><main className="mx-auto max-w-5xl px-4 py-8"><div className="mx-auto max-w-3xl"><div className="mb-6 flex items-center justify-center gap-2">{["Service","Date & Time","Your Details"].map((x,i)=><div key={x} className={`rounded-full px-4 py-2 text-xs font-bold ${step===i+1?"bg-primary text-white":"bg-white border text-muted-foreground"}`}>{i+1}. {x}</div>)}</div><section className="rounded-3xl border bg-white p-5 shadow-xl md:p-8">
 {step===1&&<><h1 className="text-3xl font-extrabold">What would you like to book?</h1><p className="mt-2 text-muted-foreground">Tap a category, then tap your service.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{GROUPS.map(g=>{const Icon=g.icon;return <button key={g.id} onClick={()=>selectCategory(g.id)} className={`rounded-2xl border-2 p-5 text-left transition ${category===g.id?"border-primary bg-primary/5":"hover:border-primary/40"}`}><Icon className="h-6 w-6 text-primary"/><b className="mt-3 block text-lg">{g.label}</b><span className="text-sm text-muted-foreground">{g.subtitle}</span></button>})}</div>{category&&<div className="mt-6"><h2 className="mb-3 font-bold">Choose service</h2><div className="grid gap-2 sm:grid-cols-2">{services.map((s:any)=><button key={s.slug} onClick={()=>chooseService(s.slug)} className={`flex items-center justify-between rounded-xl border p-4 text-left ${form.service===s.slug?"border-primary bg-primary/5":"hover:border-primary/40"}`}><span className="font-semibold">{s.name}</span><span className="text-sm text-muted-foreground">{s.duration} min</span></button>)}</div></div>}{service&&<button onClick={goSlot} className="mt-7 w-full rounded-xl bg-primary py-4 text-lg font-bold text-white">Choose Date & Time →</button>}</>}
 {step===2&&<><button onClick={()=>setStep(1)} className="mb-5 text-sm font-bold text-primary">← Change service</button><h1 className="text-3xl font-extrabold">Choose date & time</h1><p className="mt-2 text-muted-foreground">{service?.name} with <b>{artist}</b></p><input type="date" min={getIndiaDate()} value={form.date} onChange={e=>setForm({...form,date:e.target.value,time:""})} className="mt-6 w-full rounded-xl border px-4 py-4 text-lg"/>{isTuesday(form.date)?<p className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">Tuesday is closed.</p>:form.date?<div className="mt-5">{availability==="loading"?<p className="py-5 text-center">Checking available times…</p>:availability==="error"?<p className="rounded-xl bg-orange-50 p-4">Live availability is temporarily unavailable.</p>:<div className="grid grid-cols-3 gap-2">{slots.map(([time,label])=>{const no=blocked.includes(time)||isPastSlot(form.date,time);return <button key={time} disabled={no} onClick={()=>setForm({...form,time})} className={`rounded-xl border p-3 font-bold ${no?"bg-muted opacity-40":form.time===time?"border-primary bg-primary text-white":"bg-emerald-50 hover:border-primary"}`}>{label}</button>})}</div>}</div>:null}{form.time&&<button onClick={goDetails} className="mt-7 w-full rounded-xl bg-primary py-4 text-lg font-bold text-white">Continue →</button>}</>}
 {step===3&&<><button onClick={()=>setStep(2)} className="mb-5 text-sm font-bold text-primary">← Change time</button><h1 className="text-3xl font-extrabold">Almost done</h1><div className="mt-3 rounded-xl bg-primary/5 p-4 text-sm"><b>{service?.name}</b> with {artist} · {form.date} · {form.time}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="font-semibold sm:col-span-2">Name *<input autoFocus value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" placeholder="Customer / child name"/></label><label className="font-semibold sm:col-span-2">Mobile number *<input type="tel" inputMode="numeric" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" placeholder="10-digit mobile number"/></label><label className="font-semibold">Age <span className="font-normal text-muted-foreground">(optional)</span><input value={form.age} onChange={e=>setForm({...form,age:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="font-semibold">Email <span className="font-normal text-muted-foreground">(optional)</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>{isMundan&&<div className="sm:col-span-2 rounded-xl bg-orange-50 p-4"><b>Mundan location *</b><div className="mt-3 flex gap-2">{["Salon","Home"].map(x=><button type="button" key={x} onClick={()=>setForm({...form,mundanLocation:x,homeAddress:x==="Salon"?"":form.homeAddress})} className={`rounded-xl border px-5 py-2 ${form.mundanLocation===x?"bg-primary text-white":"bg-white"}`}>{x}</button>)}</div>{form.mundanLocation==="Home"&&<textarea value={form.homeAddress} onChange={e=>setForm({...form,homeAddress:e.target.value})} className="mt-3 w-full rounded-xl border p-3" placeholder="Home address"/>}</div>}</div><button disabled={submitting} onClick={submit} className="mt-7 w-full rounded-xl bg-primary py-4 text-lg font-bold text-white disabled:opacity-50">{submitting?"Booking…":"Confirm Booking"}</button><p className="mt-3 text-center text-xs text-muted-foreground">Your selected slot is checked again before confirmation.</p></>}
 </section></div></main><Footer/></div>;
}
