import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { CalendarDays, CheckCircle2, Clock3, MapPin, MessageCircle, Phone, Sparkles } from "lucide-react";
import { toast } from "sonner";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SocialSidebar from "@/components/SocialSidebar";
import SEO from "@/components/SEO";
import KidsStickers from "@/components/KidsStickers";
import { BOOKING_SERVICES, getIndiaDate, getSlotsForDate, isPastSlot, isTuesday, isValidEmail, isValidPhone } from "@/lib/booking";

const API_URL = "https://kidsalonia-ai.vercel.app";
const STYLIST = "Any Available Artist";
const PHONE = "+918130307036";
const WHATSAPP = "918130307036";
type AvailabilityState = "idle" | "loading" | "ready" | "error";
type Confirmation = { reference: string; assignedArtist?: string };

const getErrorMessage=(result:unknown,fallback:string)=>result&&typeof result==="object"&&"message" in result&&typeof result.message==="string"?result.message:fallback;
const toCalendarDate=(date:string,time:string,duration:number)=>{const start=new Date(`${date}T${time}:00+05:30`),end=new Date(start.getTime()+duration*60000),format=(v:Date)=>v.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");return{start:format(start),end:format(end)}};

const Booking=()=>{
 const [params]=useSearchParams(),requestedService=params.get("service")??"",initialService=BOOKING_SERVICES.some(i=>i.slug===requestedService)?requestedService:"";
 const [step,setStep]=useState(initialService?2:1),[submitting,setSubmitting]=useState(false),[availabilityState,setAvailabilityState]=useState<AvailabilityState>("idle"),[unavailableSlots,setUnavailableSlots]=useState<string[]>([]),[confirmation,setConfirmation]=useState<Confirmation|null>(null);
 const [form,setForm]=useState({service:initialService,childName:"",childAge:"",parentName:"",phone:"",email:"",date:"",time:"",notes:"",mundanLocation:"",homeAddress:""});
 const service=useMemo(()=>BOOKING_SERVICES.find(i=>i.slug===form.service),[form.service]),slots=useMemo(()=>getSlotsForDate(form.date),[form.date]),minDate=getIndiaDate(),isMundan=service?.slug==="mundan";

 useEffect(()=>{if(!form.date||isTuesday(form.date)||!service){setUnavailableSlots([]);setAvailabilityState("idle");return;}const controller=new AbortController();const check=async()=>{setAvailabilityState("loading");setUnavailableSlots([]);try{const results=await Promise.all(slots.map(async([time])=>{if(isPastSlot(form.date,time))return time;const query=new URLSearchParams({date:form.date,time,stylist:STYLIST,duration:String(service.duration)});const response=await fetch(`${API_URL}/api/appointments/availability?${query}`,{cache:"no-store",headers:{Accept:"application/json"},signal:controller.signal});const result:unknown=await response.json().catch(()=>null);return response.ok&&result&&typeof result==="object"&&"available" in result&&result.available===true?null:time;}));setUnavailableSlots(results.filter((t):t is string=>Boolean(t)));setAvailabilityState("ready");}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;setAvailabilityState("error");}};void check();return()=>controller.abort();},[form.date,slots,service]);

 const validateDetails=()=>{if(!form.childName.trim()||!form.parentName.trim()||!form.phone.trim())return"Please complete the child name, parent name and mobile number.";if(!isValidPhone(form.phone))return"Enter a valid 10-digit Indian mobile number.";if(!isValidEmail(form.email))return"Enter a valid email address.";if(isMundan&&!form.mundanLocation)return"Please select Mundan location: Salon or Home.";if(isMundan&&form.mundanLocation==="Home"&&!form.homeAddress.trim())return"Please enter the home address for Mundan home service.";return null;};
 const next=()=>{let error:string|null=null;if(step===1&&!service)error="Please choose a service.";if(step===2)error=validateDetails();if(step===3){if(!form.date||!form.time)error="Please select an available date and time.";else if(isTuesday(form.date))error="KidSalonia is closed on Tuesday.";else if(availabilityState!=="ready")error="Live availability must be confirmed before continuing.";else if(unavailableSlots.includes(form.time)||isPastSlot(form.date,form.time))error="That slot is unavailable for the full service duration. Please choose another time.";}if(error)return toast.error(error);setStep(c=>Math.min(4,c+1));};

 const submit=async()=>{if(!service||submitting)return;const validationError=validateDetails();if(validationError){toast.error(validationError);setStep(2);return;}setSubmitting(true);try{const query=new URLSearchParams({date:form.date,time:form.time,stylist:STYLIST,duration:String(service.duration)});const availability=await fetch(`${API_URL}/api/appointments/availability?${query}`,{cache:"no-store",headers:{Accept:"application/json"}}),availableResult:unknown=await availability.json().catch(()=>null);if(!(availability.ok&&availableResult&&typeof availableResult==="object"&&"available" in availableResult&&availableResult.available===true))throw new Error("That slot was just booked. Please choose another time.");const response=await fetch(`${API_URL}/api/appointments/website-booking`,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({parentName:form.parentName.trim(),childName:form.childName.trim(),childAge:form.childAge.trim(),phone:form.phone.trim(),email:form.email.trim()||undefined,service:service.name,stylist:STYLIST,date:form.date,time:form.time,duration:service.duration,mundanLocation:isMundan?form.mundanLocation:undefined,homeAddress:isMundan&&form.mundanLocation==="Home"?form.homeAddress.trim():undefined,notes:form.notes.trim()})});const result:any=await response.json().catch(()=>null);if(!(response.ok&&result?.success===true))throw new Error(getErrorMessage(result,"Unable to complete the booking. Please call or WhatsApp us."));setConfirmation({reference:String(result.appointmentId||`KS-${Date.now().toString().slice(-8)}`),assignedArtist:result.assignedArtist});toast.success("Appointment booked successfully.");window.scrollTo({top:0,behavior:"smooth"});}catch(error){toast.error(error instanceof Error?error.message:"Unable to complete the booking.");setStep(3);}finally{setSubmitting(false);}};

 if(confirmation&&service){const calendar=toCalendarDate(form.date,form.time,service.duration),location=isMundan&&form.mundanLocation==="Home"?form.homeAddress:"Ground Floor, A-19 JMD Suburbio 2, Gurugram",calendarUrl=`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(`KidSalonia - ${service.name}`)}&dates=${calendar.start}/${calendar.end}&details=${encodeURIComponent(`Booking reference: ${confirmation.reference}`)}&location=${encodeURIComponent(location)}`,whatsappText=encodeURIComponent(`Hi KidSalonia, my booking ${confirmation.reference} is confirmed for ${service.name}${isMundan?` (${form.mundanLocation})`:""} on ${form.date} at ${form.time}.`);return <div className="min-h-screen bg-background"><SEO title="Booking Confirmed | KidSalonia" description="Your KidSalonia appointment has been confirmed." canonical="https://www.kidsalonia.com/book" noIndex/><Header/><main className="mx-auto max-w-3xl px-4 py-16 text-center"><CheckCircle2 className="mx-auto h-20 w-20 text-emerald-500"/><h1 className="mt-6 text-4xl font-extrabold">Your appointment is booked!</h1><p className="mt-4 text-lg text-muted-foreground">We look forward to serving {form.childName}.</p><dl className="mx-auto mt-8 max-w-xl rounded-3xl border bg-card p-7 text-left shadow-sm"><div><dt className="font-bold">Booking reference</dt><dd>{confirmation.reference}</dd></div><div className="mt-3"><dt className="font-bold">Service</dt><dd>{service.name}</dd></div>{isMundan&&<div className="mt-3"><dt className="font-bold">Mundan location</dt><dd>{form.mundanLocation}{form.mundanLocation==="Home"?` — ${form.homeAddress}`:""}</dd></div>}<div className="mt-3"><dt className="font-bold">Artist</dt><dd>{confirmation.assignedArtist||"Assigned by salon"}</dd></div><div className="mt-3"><dt className="font-bold">Date and time</dt><dd>{form.date} at {form.time}</dd></div><div className="mt-3"><dt className="font-bold">Duration</dt><dd>About {service.duration} minutes</dd></div></dl><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href={calendarUrl} target="_blank" rel="noreferrer" className="rounded-full bg-primary px-6 py-3 font-bold text-primary-foreground">Add to Google Calendar</a><a href={`https://wa.me/${WHATSAPP}?text=${whatsappText}`} target="_blank" rel="noreferrer" className="rounded-full bg-emerald-500 px-6 py-3 font-bold text-white">WhatsApp confirmation</a></div></main><Footer/></div>}

 return <div className="min-h-screen bg-gradient-to-b from-pink-50 via-white to-orange-50"><SEO title="Book Salon Appointment in Gurgaon | KidSalonia" description="Book kids and adults salon services with live duration-aware availability at KidSalonia Gurgaon." canonical="https://www.kidsalonia.com/book"/><Header/><SocialSidebar/><main className="mx-auto max-w-6xl px-4 py-12 md:py-20"><div className="text-center"><p className="font-bold uppercase tracking-widest text-primary">Live online booking</p><h1 className="mt-3 text-4xl font-extrabold md:text-6xl">Book your salon visit</h1><p className="mx-auto mt-4 max-w-2xl text-lg text-muted-foreground">Choose any available service and reserve an artist for the full service duration.</p></div><div className="mx-auto mt-10 grid max-w-5xl gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="min-w-0 rounded-3xl border bg-white p-5 shadow-xl md:p-8"><ol className="mb-8 grid grid-cols-4 gap-2">{["Service","Details","Slot","Review"].map((label,index)=><li key={label} className="text-center"><div className={`mx-auto flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${step>=index+1?"bg-primary text-primary-foreground":"bg-muted text-muted-foreground"}`}>{index+1}</div><p className="mt-2 text-xs font-semibold">{label}</p></li>)}</ol>
 {step===1&&<div><h2 className="text-2xl font-bold">Choose a service</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{BOOKING_SERVICES.map(item=><button key={item.slug} type="button" onClick={()=>setForm({...form,service:item.slug,time:"",mundanLocation:item.slug==="mundan"?form.mundanLocation:"",homeAddress:item.slug==="mundan"?form.homeAddress:""})} className={`rounded-2xl border p-5 text-left ${form.service===item.slug?"border-primary bg-primary/5 ring-2 ring-primary/20":"hover:border-primary"}`}><span className="block font-bold">{item.name}</span><span className="mt-2 block text-sm text-muted-foreground">About {item.duration} minutes</span></button>)}</div></div>}
 {step===2&&<div><h2 className="text-2xl font-bold">Customer details</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Child / Customer name *<input value={form.childName} onChange={e=>setForm({...form,childName:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Age<input value={form.childAge} onChange={e=>setForm({...form,childAge:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Parent / Contact name *<input value={form.parentName} onChange={e=>setForm({...form,parentName:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Mobile number *<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} type="tel" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold sm:col-span-2">Email (optional)<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} type="email" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>{isMundan&&<div className="sm:col-span-2 rounded-2xl border border-orange-200 bg-orange-50 p-5"><p className="font-bold">Mundan Location *</p><div className="mt-3 flex gap-3">{["Salon","Home"].map(loc=><button key={loc} type="button" onClick={()=>setForm({...form,mundanLocation:loc,homeAddress:loc==="Salon"?"":form.homeAddress})} className={`rounded-xl border px-6 py-3 font-bold ${form.mundanLocation===loc?"bg-primary text-primary-foreground":"bg-white"}`}>{loc}</button>)}</div>{form.mundanLocation==="Home"&&<label className="mt-4 block text-sm font-semibold">Home address *<textarea value={form.homeAddress} onChange={e=>setForm({...form,homeAddress:e.target.value})} rows={3} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" placeholder="Enter complete Gurugram home address"/></label>}</div>}</div></div>}
 {step===3&&<div><h2 className="text-2xl font-bold">Choose date and time</h2><label className="mt-6 block text-sm font-semibold">Appointment date<input type="date" min={minDate} value={form.date} onChange={e=>setForm({...form,date:e.target.value,time:""})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>{isTuesday(form.date)?<p className="mt-4 rounded-xl bg-red-50 p-4 font-semibold text-red-700">Tuesday is closed. Please choose another date.</p>:form.date?<div className="mt-6">{availabilityState==="loading"?<p>Checking full-duration availability…</p>:availabilityState==="error"?<p className="rounded-xl bg-amber-50 p-4">Live availability is temporarily unavailable.</p>:<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{slots.map(([time,label])=>{const unavailable=unavailableSlots.includes(time)||isPastSlot(form.date,time);return <button key={time} type="button" disabled={unavailable} onClick={()=>setForm({...form,time})} className={`rounded-2xl border p-4 font-bold ${unavailable?"cursor-not-allowed bg-muted opacity-60":form.time===time?"border-primary bg-primary text-primary-foreground":"border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{label}<span className="mt-1 block text-xs">{unavailable?"No artist available":"Available"}</span></button>})}</div>}</div>:<p className="mt-4 text-sm text-muted-foreground">Select a date to check live availability.</p>}</div>}
 {step===4&&service&&<div><h2 className="text-2xl font-bold">Review your booking</h2><dl className="mt-6 space-y-3 rounded-2xl bg-muted/40 p-6"><div><dt className="font-bold">Service</dt><dd>{service.name}</dd></div><div><dt className="font-bold">Duration</dt><dd>{service.duration} minutes</dd></div>{isMundan&&<div><dt className="font-bold">Mundan location</dt><dd>{form.mundanLocation}{form.mundanLocation==="Home"?` — ${form.homeAddress}`:""}</dd></div>}<div><dt className="font-bold">Customer</dt><dd>{form.childName}</dd></div><div><dt className="font-bold">Contact</dt><dd>{form.parentName} · {form.phone}</dd></div><div><dt className="font-bold">Date and time</dt><dd>{form.date} at {form.time}</dd></div></dl><label className="mt-5 block text-sm font-semibold">Notes or special requests<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={4} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label></div>}
 <div className="mt-8 flex justify-between gap-3"><button type="button" disabled={step===1||submitting} onClick={()=>setStep(c=>Math.max(1,c-1))} className="rounded-full border px-6 py-3 font-bold disabled:opacity-40">Back</button>{step<4?<button type="button" disabled={availabilityState==="loading"} onClick={next} className="rounded-full bg-primary px-7 py-3 font-bold text-primary-foreground disabled:opacity-50">Continue</button>:<button type="button" disabled={submitting} onClick={()=>void submit()} className="rounded-full bg-primary px-7 py-3 font-bold text-primary-foreground disabled:opacity-50">{submitting?"Confirming…":"Confirm booking"}</button>}</div></section><aside className="space-y-4"><div className="rounded-3xl border bg-white p-6 shadow-sm"><Sparkles className="text-primary"/><h2 className="mt-3 text-xl font-bold">Smart booking</h2><ul className="mt-4 space-y-3 text-sm text-muted-foreground"><li className="flex gap-2"><Clock3 size={18}/> Full service duration reserved</li><li className="flex gap-2"><CalendarDays size={18}/> Live artist availability</li><li className="flex gap-2"><MapPin size={18}/> Salon or Mundan home service</li></ul></div><a href={`tel:${PHONE}`} className="flex items-center gap-3 rounded-2xl bg-orange-500 p-5 font-bold text-white"><Phone/> Need help? Call us</a><a href={`https://wa.me/${WHATSAPP}`} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-2xl bg-emerald-500 p-5 font-bold text-white"><MessageCircle/> WhatsApp us</a><Link to="/offers" className="block rounded-2xl border bg-white p-5 text-center font-bold text-primary">View current offers</Link></aside></div></main><Footer/></div>;
};
export default Booking;
