import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SocialSidebar from "@/components/SocialSidebar";
import SEO from "@/components/SEO";
import { BOOKING_SERVICES, getIndiaDate, getSlotsForDate, isPastSlot, isTuesday, isValidEmail, isValidPhone } from "@/lib/booking";

const API_URL="https://kidsalonia-ai.vercel.app", WHATSAPP="918130307036";
type AvailabilityState="idle"|"loading"|"ready"|"error";
type Category="hair"|"nail"|"pedi-mani";
const GROUPS:{id:Category;label:string;artist:string;slugs:string[]}[]=[
 {id:"hair",label:"Haircut by Rajiv",artist:"Rajiv",slugs:["kids-haircut","baby-first-haircut","boy-haircut","girl-haircut","adult-haircut","mundan","hair-wash","hair-styling","hair-spa","lice-treatment"]},
 {id:"nail",label:"Nail Art by Pooja",artist:"Pooja",slugs:["kids-nail-art","adult-nail-art","gel-polish"]},
 {id:"pedi-mani",label:"Pedicure by Julie",artist:"Julie",slugs:["kids-manicure","adult-manicure","kids-pedicure","adult-pedicure"]},
];
const groupFor=(slug:string)=>GROUPS.find(g=>g.slugs.includes(slug));
const errorMessage=(r:unknown,f:string)=>r&&typeof r==="object"&&"message" in r&&typeof r.message==="string"?r.message:f;

export default function BookingV2(){
 const [params]=useSearchParams(); const requested=params.get("service")??""; const initial=BOOKING_SERVICES.some(s=>s.slug===requested)?requested:""; const initialGroup=groupFor(initial);
 const [step,setStep]=useState(initial?2:1),[category,setCategory]=useState<Category|"">(initialGroup?.id??""),[submitting,setSubmitting]=useState(false),[availability,setAvailability]=useState<AvailabilityState>("idle"),[blocked,setBlocked]=useState<string[]>([]),[reference,setReference]=useState("");
 const [form,setForm]=useState({service:initial,customerName:"",age:"",contactName:"",phone:"",email:"",date:"",time:"",notes:"",mundanLocation:"",homeAddress:""});
 const service=useMemo(()=>BOOKING_SERVICES.find(s=>s.slug===form.service),[form.service]); const group=groupFor(form.service); const artist=group?.artist??""; const services=GROUPS.find(g=>g.id===category)?.slugs.map(slug=>BOOKING_SERVICES.find(s=>s.slug===slug)).filter(Boolean)??[]; const slots=useMemo(()=>getSlotsForDate(form.date),[form.date]); const isMundan=form.service==="mundan";
 useEffect(()=>{if(!form.date||!service||!artist||isTuesday(form.date)){setBlocked([]);setAvailability("idle");return;}const c=new AbortController();(async()=>{setAvailability("loading");try{const r=await Promise.all(slots.map(async([time])=>{if(isPastSlot(form.date,time))return time;const q=new URLSearchParams({date:form.date,time,stylist:artist,duration:String(service.duration)});const x=await fetch(`${API_URL}/api/appointments/availability?${q}`,{cache:"no-store",headers:{Accept:"application/json"},signal:c.signal});const j:any=await x.json().catch(()=>null);return x.ok&&j?.available===true?null:time;}));setBlocked(r.filter((x):x is string=>Boolean(x)));setAvailability("ready");}catch(e){if(e instanceof DOMException&&e.name==="AbortError")return;setAvailability("error");}})();return()=>c.abort();},[form.date,service,artist,slots]);
 const validate=()=>{if(!form.customerName.trim()||!form.contactName.trim()||!form.phone.trim())return"Please complete customer name, contact name and mobile number.";if(!isValidPhone(form.phone))return"Enter a valid 10-digit Indian mobile number.";if(!isValidEmail(form.email))return"Enter a valid email address.";if(isMundan&&!form.mundanLocation)return"Please select Mundan location.";if(isMundan&&form.mundanLocation==="Home"&&!form.homeAddress.trim())return"Please enter the home address.";return null;};
 const next=()=>{let e:string|null=null;if(step===1&&(!category||!service||!artist))e="Please choose a service category and related service.";if(step===2)e=validate();if(step===3){if(!form.date||!form.time)e="Please select an available date and time.";else if(isTuesday(form.date))e="KidSalonia is closed on Tuesday.";else if(availability!=="ready"||blocked.includes(form.time)||isPastSlot(form.date,form.time))e="Please choose an available slot.";}if(e)return toast.error(e);setStep(s=>Math.min(4,s+1));};
 const submit=async()=>{if(!service||!artist||submitting)return;const e=validate();if(e)return toast.error(e);setSubmitting(true);try{const q=new URLSearchParams({date:form.date,time:form.time,stylist:artist,duration:String(service.duration)});const a=await fetch(`${API_URL}/api/appointments/availability?${q}`,{cache:"no-store",headers:{Accept:"application/json"}});const aj:any=await a.json().catch(()=>null);if(!(a.ok&&aj?.available===true))throw new Error("That slot was just booked. Please choose another time.");const r=await fetch(`${API_URL}/api/appointments/website-booking`,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({parentName:form.contactName.trim(),childName:form.customerName.trim(),childAge:form.age.trim(),phone:form.phone.trim(),email:form.email.trim()||undefined,service:service.name,stylist:artist,date:form.date,time:form.time,duration:service.duration,mundanLocation:isMundan?form.mundanLocation:undefined,homeAddress:isMundan&&form.mundanLocation==="Home"?form.homeAddress.trim():undefined,notes:form.notes.trim()})});const j:any=await r.json().catch(()=>null);if(!(r.ok&&j?.success===true))throw new Error(errorMessage(j,"Unable to complete booking."));setReference(String(j.appointmentId||`KS-${Date.now().toString().slice(-8)}`));toast.success("Appointment booked successfully.");window.scrollTo({top:0,behavior:"smooth"});}catch(e){toast.error(e instanceof Error?e.message:"Unable to complete booking.");setStep(3);}finally{setSubmitting(false);}};
 if(reference&&service)return <div className="min-h-screen bg-background"><SEO title="Booking Confirmed | KidSalonia" description="Your KidSalonia appointment is confirmed." canonical="https://www.kidsalonia.com/book" noIndex/><Header/><main className="mx-auto max-w-3xl px-4 py-16 text-center"><CheckCircle2 className="mx-auto h-20 w-20 text-emerald-500"/><h1 className="mt-6 text-4xl font-extrabold">Your appointment is booked!</h1><div className="mx-auto mt-8 max-w-xl rounded-3xl border bg-card p-7 text-left"><p><b>Reference:</b> {reference}</p><p className="mt-2"><b>Service:</b> {service.name}</p><p className="mt-2"><b>Artist:</b> {artist}</p><p className="mt-2"><b>Date:</b> {form.date} at {form.time}</p></div><a className="mt-7 inline-block rounded-full bg-emerald-500 px-6 py-3 font-bold text-white" href={`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`Hi KidSalonia, booking ${reference} for ${service.name} with ${artist} is confirmed for ${form.date} at ${form.time}.`)}`}>WhatsApp confirmation</a></main><Footer/></div>;
 return <div className="min-h-screen bg-gradient-to-b from-pink-50 via-white to-orange-50"><SEO title="Book Salon Appointment in Gurgaon | KidSalonia" description="Choose your service, dedicated artist and live appointment slot at KidSalonia Gurgaon." canonical="https://www.kidsalonia.com/book"/><Header/><SocialSidebar/><main className="mx-auto max-w-6xl px-4 py-12"><div className="text-center"><p className="font-bold uppercase tracking-widest text-primary">Live online booking</p><h1 className="mt-3 text-4xl font-extrabold md:text-6xl">Book your salon visit</h1><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">Choose a service category first, then select the related service. Your specialist is assigned automatically.</p></div><section className="mx-auto mt-10 max-w-3xl rounded-3xl border bg-white p-5 shadow-xl md:p-8"><ol className="mb-8 grid grid-cols-4 gap-2">{["Service","Details","Slot","Review"].map((l,i)=><li key={l} className="text-center"><div className={`mx-auto flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${step>=i+1?"bg-primary text-primary-foreground":"bg-muted"}`}>{i+1}</div><p className="mt-2 text-xs font-semibold">{l}</p></li>)}</ol>
 {step===1&&<div><h2 className="text-2xl font-bold">Choose a service</h2><div className="mt-6 grid gap-5"><label className="font-semibold">1. Service category<select value={category} onChange={e=>{const v=e.target.value as Category|"";setCategory(v);setForm({...form,service:"",time:"",mundanLocation:"",homeAddress:""});}} className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">Select category</option>{GROUPS.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><label className="font-semibold">2. Related service<select disabled={!category} value={form.service} onChange={e=>setForm({...form,service:e.target.value,time:"",mundanLocation:"",homeAddress:""})} className="mt-2 w-full rounded-xl border bg-white px-4 py-3 disabled:bg-muted"><option value="">Select related service</option>{services.map((s:any)=><option key={s.slug} value={s.slug}>{s.name} — {s.duration} min</option>)}</select></label>{artist&&service&&<div className="rounded-2xl bg-primary/5 p-4"><b>Assigned specialist:</b> {artist}</div>}</div></div>}
 {step===2&&<div><h2 className="text-2xl font-bold">Customer details</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Child / Customer name *<input value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Age<input value={form.age} onChange={e=>setForm({...form,age:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Parent / Contact name *<input value={form.contactName} onChange={e=>setForm({...form,contactName:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold">Mobile *<input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-semibold sm:col-span-2">Email (optional)<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>{isMundan&&<div className="sm:col-span-2 rounded-2xl bg-orange-50 p-5"><b>Mundan location *</b><div className="mt-3 flex gap-3">{["Salon","Home"].map(x=><button type="button" key={x} onClick={()=>setForm({...form,mundanLocation:x,homeAddress:x==="Salon"?"":form.homeAddress})} className={`rounded-xl border px-5 py-2 ${form.mundanLocation===x?"bg-primary text-white":"bg-white"}`}>{x}</button>)}</div>{form.mundanLocation==="Home"&&<textarea value={form.homeAddress} onChange={e=>setForm({...form,homeAddress:e.target.value})} className="mt-3 w-full rounded-xl border p-3" placeholder="Complete Gurugram home address"/>}</div>}</div></div>}
 {step===3&&<div><h2 className="text-2xl font-bold">Choose date and time with {artist}</h2><input type="date" min={getIndiaDate()} value={form.date} onChange={e=>setForm({...form,date:e.target.value,time:""})} className="mt-6 w-full rounded-xl border px-4 py-3"/>{isTuesday(form.date)?<p className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">Tuesday is closed.</p>:form.date?<div className="mt-6">{availability==="loading"?<p>Checking {artist}'s availability…</p>:availability==="error"?<p>Live availability is temporarily unavailable.</p>:<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{slots.map(([time,label])=>{const no=blocked.includes(time)||isPastSlot(form.date,time);return <button key={time} disabled={no} onClick={()=>setForm({...form,time})} className={`rounded-xl border p-3 font-bold ${no?"opacity-40":form.time===time?"bg-primary text-white":"bg-emerald-50"}`}>{label}<small className="block">{no?"Unavailable":"Available"}</small></button>})}</div>}</div>:null}</div>}
 {step===4&&service&&<div><h2 className="text-2xl font-bold">Review your booking</h2><div className="mt-6 space-y-2 rounded-2xl bg-muted/40 p-6"><p><b>Category:</b> {group?.label}</p><p><b>Service:</b> {service.name}</p><p><b>Artist:</b> {artist}</p><p><b>Duration:</b> {service.duration} minutes</p><p><b>Customer:</b> {form.customerName}</p><p><b>Date & time:</b> {form.date} at {form.time}</p></div></div>}
 <div className="mt-8 flex justify-between">{step>1?<button onClick={()=>setStep(s=>s-1)} className="rounded-full border px-6 py-3 font-bold">Back</button>:<span/>}{step<4?<button onClick={next} className="rounded-full bg-primary px-7 py-3 font-bold text-white">Continue</button>:<button disabled={submitting} onClick={submit} className="rounded-full bg-primary px-7 py-3 font-bold text-white disabled:opacity-50">{submitting?"Booking…":"Confirm booking"}</button>}</div></section></main><Footer/></div>;
}
