import { Link } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SocialSidebar from "@/components/SocialSidebar";
import { blogs } from "@/data/blogs";
import { getDailyLocalInsights } from "@/data/dailyLocalInsights";
import SEO from "@/components/SEO";

const tones=["bg-pink-100","bg-sky-100","bg-amber-100","bg-emerald-100","bg-violet-100","bg-rose-100"];
const Insights=()=>{const daily=getDailyLocalInsights();const visible=[...daily,...blogs].filter(b=>new Date(b.date)<=new Date()).sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());return <div className="flex flex-col min-h-screen bg-[#fff9fc]"><SEO title="Kids Care Blog & Local Gurugram Insights | KidSalonia" description="Daily KidSalonia guides covering kids haircuts, Mundan, nail art, manicure, pedicure, hair care and local Gurugram parent tips." canonical="https://www.kidsalonia.com/insights"/><Header/><SocialSidebar/>
<section className="relative overflow-hidden bg-gradient-to-br from-[#ffddea] via-[#eee4ff] to-[#dff5ff] py-16 md:py-20"><span className="absolute left-[7%] top-8 text-5xl">🌈</span><span className="absolute right-[8%] top-10 text-5xl">☁️</span><div className="relative max-w-4xl mx-auto px-6 text-center"><div className="inline-block bg-white/80 rounded-full px-5 py-2 font-bold text-primary shadow-sm">📅 Daily KidSalonia Parent & Local Guide</div><h1 className="text-4xl md:text-6xl font-black text-[#4b2677] mt-5">Fresh local tips, every day ✨</h1><p className="text-lg text-[#665678] mt-4 max-w-2xl mx-auto">Daily useful guides rotating through KidSalonia services and nearby Gurugram areas—without repeating the same keyword page.</p><div className="flex flex-wrap justify-center gap-3 mt-7"><span className="bg-white rounded-full px-4 py-2">✂️ Haircuts</span><span className="bg-white rounded-full px-4 py-2">👶 Mundan</span><span className="bg-white rounded-full px-4 py-2">💅 Nails</span><span className="bg-white rounded-full px-4 py-2">🧴 Hair Care</span><span className="bg-white rounded-full px-4 py-2">📍 Gurugram</span></div></div></section>
<section className="bg-gradient-to-b from-[#fff9fc] to-[#f2fbff] py-14"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-7">{visible.map((blog,i)=><Link key={blog.slug} to={`/insights/${blog.slug}`} className={`${tones[i%tones.length]} group rounded-[2rem] p-3 border-4 border-white shadow-md hover:-translate-y-1 hover:shadow-xl transition`}><div className="overflow-hidden rounded-[1.5rem]"><img src={blog.image} alt={blog.title} className="w-full h-56 object-cover group-hover:scale-105 transition-transform duration-300"/></div><div className="p-4"><div className="flex justify-between items-center gap-2 mb-3"><span className="bg-white/90 rounded-full px-3 py-1 text-xs font-bold">{blog.category}</span><span className="text-xs text-muted-foreground">{blog.readTime}</span></div><p className="text-xs font-semibold text-muted-foreground mb-2">📅 {blog.date}</p><h2 className="font-black text-[#3f216f] text-xl leading-snug group-hover:text-primary transition">{blog.title}</h2><p className="text-sm text-muted-foreground mt-3 line-clamp-3">{blog.excerpt}</p><div className="mt-5 font-black text-primary">Read local guide → ⭐</div></div></Link>)}</div></div></section><Footer/></div>};
export default Insights;
